spring:
  profiles:
    active: dev
  application:
    name: award-master-service

root:
  service:
    name: Award Master Service
    description: Award Master Service to maintain photographer's award details
    version: v1
    usage: Proprietary Usage
    owner: Balarka Brahma
    website: NA
    officialemail: balarka.brahma@gmail.com
    license: Public API Lincense
    baseurl: /service/fotos
    moduleurl: ${root.service.baseurl}/${root.service.version}/award

