server:
  port: 8000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

logging:
  level:
    com:
      fotos:
        orchestrator:
          master:
            service: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG