spring:
  profiles:
    active: dev
  application:
    name: fotos-orchestrator-service

root:
  service:
    name: Orchestrator Service
    description: Orchestrator Service to control different other services
    version: v1
    usage: Proprietary Usage
    owner: Balarka Brahma
    website: NA
    officialemail: balarka.brahma@gmail.com
    license: Public API Lincense
    baseurl: /service/fotos
    moduleurl: ${root.service.baseurl}/${root.service.version}/orchestrator